version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    env_file: ./server/.env
    ports: ["5000:5000"]
    depends_on: [mongo]
    volumes:
      - ./server:/app
    command: npm run dev

  client:
    build: ./client
    env_file: ./client/.env
    ports: ["5173:5173"]
    depends_on: [server]
    volumes:
      - ./client:/app
    command: npm run dev

volumes:
  mongo_data:
